//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunPay_Grishenko
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int IdDeal { get; set; }
        public int IdPlayer_Sender { get; set; }
        public int IdPlayer_Recipient { get; set; }
        public int IdItem { get; set; }
        public System.DateTime DateOfCreation { get; set; }
    
        public virtual Items Items { get; set; }
    }
}
