//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunPay_Grishenko
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameAccoun
    {
        public int IdGameAccoun { get; set; }
        public string GameTitle { get; set; }
        public int IdPlayer { get; set; }
        public string GameCurrency { get; set; }
        public int Level { get; set; }
        public int IdItem { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Player Player { get; set; }
    }
}
