//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunPay_Grishenko
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    
    
    public partial class Entities1 : DbContext
    {

        private static Entities1 _context;

        public static Entities1 GetContext()
        { 
            if( _context == null )
                _context = new Entities1();
            return _context;
        }

        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Deal> Deal { get; set; }
        public DbSet<GameAccoun> GameAccoun { get; set; }
        public DbSet<Items> Items { get; set; }
        public DbSet<Partnership> Partnership { get; set; }
        public DbSet<Player> Player { get; set; }
    }
}
