//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunPay_Grishenko
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partnership
    {
        public int IdPartnership { get; set; }
        public int IdPlayer_1 { get; set; }
        public int IdPlayer_2 { get; set; }
        public System.DateTime StartDateOfCooperation { get; set; }
        public System.DateTime EndDateOfCooperation { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
